# -*- Makefile -*-
#
# This package is free software; you can redistribute it and/or
# modify it under terms of the GNU General Public License as
# published by the Free Software Foundation; either version 3, or
# (at your option) any later version. It is distributed in the
# hope that it will be useful, but WITHOUT ANY WARRANTY; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.
#
# You should have received a copy of the GNU General Public License
# along with this program; see the file COPYING3. If not, see
# <http://www.gnu.org/licenses/>.
#
# Copyright Simon Wright <simon@pushface.org>

# To avoid disaster
ifndef DIST
  $(error Must define DIST)
endif

all: ; $(error Only to be used to build distributions)

dist::

THIS := test-common

DISTRIBUTION_FILES =				\
  containing.adb				\
  containing.ads				\
  dispatching.adb				\
  dispatching.ads				\
  iteration.adb					\
  iteration.ads					\
  last_chance_handler.adb			\
  last_chance_handler.ads			\
  memory_streams.adb				\
  memory_streams.ads				\
  so.adb					\
  so.ads					\
  streams.adb					\
  streams.ads					\
  strings.adb					\
  strings.ads

dist:: $(DISTRIBUTION_FILES)
	mkdir $(DIST)/$(THIS)
	tar cf - $(DISTRIBUTION_FILES) |	\
	  tar xvf - -C $(DIST)/$(THIS)

.PHONY: all dist
