# -*- Makefile -*-
#
# This package is free software; you can redistribute it and/or
# modify it under terms of the GNU General Public License as
# published by the Free Software Foundation; either version 3, or
# (at your option) any later version. It is distributed in the
# hope that it will be useful, but WITHOUT ANY WARRANTY; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.
#
# You should have received a copy of the GNU General Public License
# along with this program; see the file COPYING3. If not, see
# <http://www.gnu.org/licenses/>.
#
# Copyright Simon Wright <simon@pushface.org>

# To avoid disaster
ifndef DIST
  $(error Must define DIST)
endif

all: ; $(error Only to be used to build distributions)

dist::

THIS := test-arduino-due

DISTRIBUTION_FILES =				\
  Makefile

DISTRIBUTION_FILES +=				\
  first.gpr					\
  program.gpr					\
  testbed.gpr

DISTRIBUTION_FILES +=				\
  first.adb					\
  first_task.adb				\
  first_task.ads				\
  handler.adb					\
  handler.ads					\
  interrupts.adb				\
  interrupts.ads				\
  program.adb					\
  program.ads					\
  registers-atsam3x8-peripheral_identifiers.ads	\
  registers-atsam3x8-pio.ads			\
  registers-atsam3x8-pmc.ads			\
  registers-atsam3x8.ads			\
  registers-cortex-nvic.ads			\
  registers-cortex-systick.ads			\
  registers-cortex.ads				\
  registers.ads					\
  testbed.adb					\
  time.adb					\
  time.ads

dist:: $(DISTRIBUTION_FILES)
	mkdir $(DIST)/$(THIS)
	tar cf - $(DISTRIBUTION_FILES) | \
	  tar xvf - -C $(DIST)/$(THIS)

.PHONY: all dist
